### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gusthoff** [chmike/fpsqrt#1]
There is no indication about the actual license for this repository. Could you please clarify this? I'm thinking about reusing your algorithm in an exercise...

**Comment by chmike** [comment]
I will do that ASAP as soon as I get access to a computer. It will be the MIT license. You may freely use it for your exercises. Thanks for your interest.

**Comment by chmike** [comment]
It's done.

**Comment by gusthoff** [comment]
Thanks a lot, @chmike !
